spring.application.name=API-GATEWAY
server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
management.endpoints.web.exposure.includes=*

#Product Service Route
spring.cloud.gateway.mvc.route[0].id=product-service
spring.cloud.gateway.mvc.route[0].uri=lb://PRODUCT-SERVICE
spring.cloud.gateway.mvc.route[0].pridicates[0]=Path=/products/**

#inventory Service Route
spring.cloud.gateway.mvc.route[1].id=inventory-service
spring.cloud.gateway.mvc.route[1].uri=lb://INVENTORY-SERVICE
spring.cloud.gateway.mvc.route[1].predicates[0]=Path=/inventory/**

#user Service Route
spring.cloud.gateway.mvc.route[2].id=user-service
spring.cloud.gateway.mvc.route[2].uri=lb://USER-SERVICE
spring.cloud.gateway.mvc.route[2].predicates[0]=Path=/users/**