spring.application.name=USER-SERVICE
jwt.secret=${JWT_SECRET:multi-warehouse-order-fulfillment-system-jwt-secret-key-2026}
jwt.expiration=${JWT_EXPIRATION:3600000}

server.port=8083

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format-sql=true

spring.graphql.graphiql.enabled=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

management.endpoints.web.exposure.include=*
